name: cite_finder_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get:
  timeago: ^3.3.0
  file_picker: ^5.2.10
  mime_type: ^1.0.0
  image_picker: ^0.8.5+3
  geolocator: ^9.0.2
  google_maps_flutter: ^2.1.12
  video_player: ^2.4.7
  google_maps_flutter_web: ^0.4.0+2
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.3
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  firebase_core: ^2.10.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  flutter_slidable: ^3.0.0
  dash_chat_2: ^0.0.17
  carousel_slider: ^4.0.0
  typesense: ^0.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LatoLight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
