name: cite_finder_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  get_storage: ^2.0.3
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.6.3
  firebase_storage: ^10.3.5
  firebase_core: ^1.20.1
  font_awesome_flutter: ^10.1.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: LatoBold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: LatoLight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
