// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTAt4rpnZw68SR8Sq7WyRnCotr7kIOdrs',
    appId: '1:198222666676:web:e7792e64033ccb25ebf0e1',
    messagingSenderId: '198222666676',
    projectId: 'citefinder',
    authDomain: 'citefinder.firebaseapp.com',
    storageBucket: 'citefinder.appspot.com',
    measurementId: 'G-MFE59Y48BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFGla93B838ES2u5KQ3vOyieG-XITokI',
    appId: '1:198222666676:android:ea2d66af8a131d7eebf0e1',
    messagingSenderId: '198222666676',
    projectId: 'citefinder',
    storageBucket: 'citefinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADApmaQpZbse45BwboaGaMROyPmuyZKos',
    appId: '1:198222666676:ios:a8c9f456ec59a1cbebf0e1',
    messagingSenderId: '198222666676',
    projectId: 'citefinder',
    storageBucket: 'citefinder.appspot.com',
    androidClientId: '198222666676-mc5maaa0sqlqui96jus2094shnir796f.apps.googleusercontent.com',
    iosClientId: '198222666676-4o6j76gcjj73uu2uhfavda6tk3iaoa3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.citeFinderAdmin',
  );
}
